// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    // 운영(Vercel Postgres)용 마이그레이션
    // (기존 sqlite용 migrations는 prisma/migrations에 남아있어도 되지만,
    // provider가 postgresql로 바뀌면 sqlite SQL이 깨질 수 있어 별도 폴더로 분리합니다.)
    path: "prisma/migrations_pg",
  },
  datasource: {
    // Vercel Postgres 연동 시 자동으로 세팅되는 env 이름들도 지원
    url:
      process.env["DATABASE_URL"] ||
      process.env["POSTGRES_PRISMA_URL"] ||
      process.env["POSTGRES_URL_NON_POOLING"] ||
      process.env["POSTGRES_URL"],
  },
});
