"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { generatePdfFirstPageThumbDataUrl } from "@/app/_components/pdfFirstPageThumbCache";
import { useRouter } from "next/navigation";

type Props = {
  textbookId: string;
  hasThumbnail: boolean;
  autoGenerate?: boolean;
};

export default function TextbookThumbnailGenerator({ textbookId, hasThumbnail, autoGenerate = true }: Props) {
  const router = useRouter();
  const [status, setStatus] = useState<"idle" | "generating" | "saving" | "done" | "error">(
    hasThumbnail ? "done" : "idle"
  );
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);

  const handleGenerate = useCallback(async () => {
    setStatus("generating");
    setErrorMsg(null);

    try {
      // 1. PDF에서 첫 페이지 추출하여 이미지 생성
      const dataUrl = await generatePdfFirstPageThumbDataUrl({
        src: `/api/textbooks/${textbookId}/view`,
        targetWidth: 300, // 고해상도 썸네일
      });

      setStatus("saving");

      // 2. 서버에 저장
      const res = await fetch(`/api/admin/textbooks/${textbookId}/thumbnail`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ thumbnailDataUrl: dataUrl }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "SAVE_FAILED");
      }

      setStatus("done");
      router.refresh();
    } catch (e) {
      console.error("[TextbookThumbnailGenerator]", e);
      setErrorMsg(String((e as Error)?.message || e));
      setStatus("error");
    }
  }, [textbookId, router]);

  // 자동 생성: 썸네일이 없고 autoGenerate가 true일 때
  useEffect(() => {
    if (autoGenerate && !hasThumbnail && !hasAutoGenerated.current && status === "idle") {
      hasAutoGenerated.current = true;
      // 약간의 지연 후 자동 생성 시작
      const timer = setTimeout(() => {
        handleGenerate();
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [autoGenerate, hasThumbnail, status, handleGenerate]);

  if (status === "done") {
    return (
      <span className="inline-flex items-center gap-1 text-xs text-green-400">
        <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 20 20">
          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
        </svg>
        썸네일 완료
      </span>
    );
  }

  if (status === "generating" || status === "saving") {
    return (
      <span className="inline-flex items-center gap-1.5 text-xs text-white/50">
        <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
        </svg>
        {status === "generating" ? "생성 중..." : "저장 중..."}
      </span>
    );
  }

  if (status === "error") {
    return (
      <div className="flex items-center gap-2">
        <span className="text-xs text-red-400" title={errorMsg || undefined}>실패</span>
        <button
          type="button"
          onClick={handleGenerate}
          className="text-xs text-white/50 hover:text-white underline"
        >
          재시도
        </button>
      </div>
    );
  }

  return (
    <button
      type="button"
      onClick={handleGenerate}
      className="inline-flex items-center gap-1.5 rounded-lg bg-white/5 px-2.5 py-1.5 text-xs text-white/70 transition-colors hover:bg-white/10 hover:text-white"
    >
      <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
      썸네일 생성
    </button>
  );
}

